inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails   # rubocop-railsを適用

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable    # ← 新しい規約が登録された場合に、適用するかどうかの判定
  Exclude:
    - 'bin/**'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'Gemfile'
    - 'app/models/application_record.rb'

Metrics/ClassLength:
  Max: 500

Layout/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'db/migrate/*'
    - 'db/data/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'db/migrate/*'
    - 'db/data/*'

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/*'
    - 'db/data/*'

Layout/EndOfLine:
  Enabled: False

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  AutoCorrect: false
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'db/data/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/controllers/**/*_controller.rb'